version: '2.2'
services:

  # The Application
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ${PROJECT_PATH}:/var/www
    depends_on:
      - redis
    environment:
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
    env_file: .env

  # The Web Server
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ${PROJECT_PATH}:/var/www
    ports:
      - 80:80
    env_file: .env

  # redis
  redis:
    container_name: redis
    image: redis:4.0-alpine
    ports:
      - 6380:6379
    volumes:
      - redisdata:/data
  smtp:
    container_name: docker_smtp
    image: schickling/mailcatcher
    ports:
      - 1090:1080

#    # elastic search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  redisdata:
  esdata:
