version: '2'
services:

  # The Application
  app:
    container_name: docker_app
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ${PROJECT_PATH}:/var/www
    env_file: .env

  # The Web Server
  web:
    container_name: docker_web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ${PROJECT_PATH}:/var/www
    ports:
      - 8080:80
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:database
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3309:80

  # The Database
  database:
    container_name: docker_db
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
        - "3306:3306"
    env_file: .env
  # redis
  redis:
    image: redis:4.0-alpine
    volumes:
      - redisdata:/data
  smtp:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

volumes:
  dbdata:
      driver: "local"
  redisdata:
      driver: "local"
