version: '2'
services:

  # The Application
  app:
    container_name: neolog_app
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ${PROJECT_PATH}:/var/www
    depends_on:
      - database
#      - redis
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=neolog
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
#      - CACHE_DRIVER=redis
#      - SESSION_DRIVER=redis
    env_file: .env

  # The Web Server
  web:
    container_name: neolog_web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ${PROJECT_PATH}:/var/www
    ports:
      - 8080:80
    env_file: .env

  phpmyadmin:
    container_name: neolog_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    environment:
      PMA_ARBITRARY: 1
      MYSQL_DATABASE: neolog
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3309:80

  # The Database
  database:
    container_name: neolog_db
    image: mysql:5.6
    volumes:
      - neologdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=neolog
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3307:3306
  # redis
#  redis:
#    container_name: neolog_redis
#    image: redis:4.0-alpine
#    ports:
#      - 6380:6379
#    volumes:
#      - redisdata:/data
#  smtp:
#    container_name: neolog_smtp
#    image: schickling/mailcatcher
#    ports:
#      - 1080:1080

#    # elastic search
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
#    container_name: neolog_es
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300

volumes:
  neologdata:
#  redisdata:
##    driver: "local"
#  esdata:
#    driver: "local"
