version: '2'
services:
  jenkins:
    container_name: jenkins
    image: 'jenkins/jenkins:lts'
    labels:
      kompose.service.type: nodeport
    ports:
    - '8080:8080'
    - '50000:50000'
    volumes:
    - './jenkins/config:/jenkins_config'
    - './jenkins/home:/var/jenkins_home'
volumes:
  jenkins_data:
    driver: local
